### ISSUE TITLE
rebase interattivo

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/helloworld#1]
puoi esercitarti con questa repo a fare i rebase interattivi

**Comment by Teodoro777** [comment]
Fatto, anche se qui non avevo delle divergenze tra branch diversi e quindi
il rebase l'ho fatto al secondo commit a partire da sotto

2015-12-28 16:41 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
prova a togliere il commit 8e25891 con un altro rebase interattivo

**Comment by Teodoro777** [comment]
Ok ma quando non ho una divergenza tra branch come capisco dove fare il
rebase?

2015-12-29 16:04 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
il rebase va fatto sul genirore che vuoi tenere.
nel caso di helloworld hai tre commit e devi eliminare il secondo, quindi
ti metti sull'ultimo e chiedi il rebase sul primo. la lista che ti uscirà
sarà composta dal secondo e dal terzo, uno lo tieni con pick e l'altro lo
fai sparire con squash

2015-12-29 16:43 GMT+01:00 Teodoro777 <notifications@github.com>:

**Comment by Teodoro777** [comment]
Salvo ed esco da qui ma mi da l'errore: "Cannot 'squash' without a previous
commit"

2015-12-29 16:45 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
forse hai messo squash al primo della lista che ti esce. devi metterlo al
secondo

2015-12-29 16:56 GMT+01:00 Teodoro777 <notifications@github.com>:

**Comment by Teodoro777** [comment]
Ho dimenticato l'allegato ovviamente...

2015-12-29 16:56 GMT+01:00 Teodoro Coluccio <teodoro.coluccio@gmail.com>:

**Comment by Teodoro777** [comment]
Ma io devo far sparire proprio il primo..

Il giorno 29 dicembre 2015 16:59, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Stranamente ho fatto così e ha cancellato proprio quello che volevo..

Il giorno 29 dicembre 2015 17:04, Teodoro Coluccio <
teodoro.coluccio@gmail.com> ha scritto:

**Comment by FabioZTessitore** [comment]
allora. quello non cancella proprio niente. hai due commit che devono
essere fusi in uno solo. Mo' o sparisce uno o l'altro non cambia niente, la
fusione è sempre la stessa. Poi decidi il messaggio che vuoi dare a questo
commit risultante

Il giorno 29 dicembre 2015 17:07, Teodoro777 <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
visto che bella repo? sembra che hai fatto tutto in una volta haha

**Comment by Teodoro777** [comment]
Ahhh capito!

Il giorno 29 dicembre 2015 17:08, Fabio Z Tessitore <
notifications@github.com> ha scritto:
