### ISSUE TITLE
Sfera

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/Helloworld#7]
Creare un programma sfera.py che chieda all'utente
il raggio di una sfera (intero) e ne stampi superficie e volume

Note:
Per portare a termine il compito e'
necessaria la costante matematica pi greco.
Si puo' definire una variabile assegnandole tale valore:
```python
pi = 3.141592654
```
Oppure si puo' utilizzare quello gia'
definita nella libreria matematica:
```python
import math

...

math.pi

...
```

**Comment by Teodoro777** [comment]
Fatto

2016-02-03 18:16 GMT+00:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by Teodoro777** [comment]
Mi piace sto python ahah

2016-02-03 18:56 GMT+00:00 Teodoro Coluccio <teodoro.coluccio@gmail.com>:

**Comment by FabioZTessitore** [comment]
Prima di tutto correggi il commento iniziale, sennò fai le figuracce.

Poi controllati le formule, fai attenzione anche ai tipi

**Comment by Teodoro777** [comment]
Volevo dire DA un raggio non "di" un raggio ahah

Il mercoledì 3 febbraio 2016, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
il volume continua a non essere calcolato bene

**Comment by Teodoro777** [comment]
Ora dovrebbe andar bene

Inviato da iPad

**Comment by FabioZTessitore** [comment]
niente da fare, prima di inviare soluzioni per tentativo, fai qualche calcolo e cerca di trovarti

**Comment by Teodoro777** [comment]
Sbaglio pechè 4/3 me lo arrotonda ad 1 e quindi è come se non lo facesse,
non mi ricordo come si cambia il tipo

2016-02-03 22:08 GMT+00:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Ti ho mandato le istruzioni in quei file. Stai diventando pigro

Il mercoledì 3 febbraio 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Sì infatti sto provando a fare quel 4/3 in tutti i modi ma esce sempre uno..
Per regola si dovrebbe fare float (4/3) ma mi esce 1.0

Il giorno 4 febbraio 2016 06:58, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Haha. Leggi bene cosa ti ho mandato

Il giovedì 4 febbraio 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Passiamo avanti

Il giorno 4 febbraio 2016 16:27, Fabio Z Tessitore <notifications@github.com
